Copr: initial native coprWatchBuild
copr-cli sleeps 30s (support multiple builds), here we sleep 20s (only one build)

since copr wait-build can fail like
"
Something went wrong:
Error: Unable to connect to https://copr.fedorainfracloud.org/api_3/.
"

idea is to eventually catch such errors and retry