GH action: disable 8.2 due to graphviz errors
Data/GraphViz/Attributes.hs:1040:27: error:
Error:     Ambiguous occurrence ‘empty’
    It could refer to either ‘Data.GraphViz.Types.Parsing.empty’,
                             imported from ‘Data.GraphViz.Types.Parsing’ at Data/GraphViz/Attributes.hs:146:1-34
                             (and originally defined in ‘GHC.Base’)
                          or ‘Data.GraphViz.Types.Printing.empty’,
                             imported from ‘Data.GraphViz.Types.Printing’ at Data/GraphViz/Attributes.hs:147:1-35
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
     |
1040 |     unqtDot FilledArrow = empty
     |                           ^^^^^